# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone test repo
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        owner: 'trentonwallis'
        repository: 'remote-tests'
        token: ${{secrets.REMOTE_TESTING_PAT}}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        ls
        ls
        cp ./hw.py ./trenton_testing/hw.py
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest
